### ISSUE TITLE
Investigate accommodating ITK remote module dependencies

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction#11]
Investigate whether ITK remote module dependencies can be accommodated via input parameters.

Example 1: ITKBSplineGradient depends on ITKMeshToPolyData.
 - For cxx builds, can we at minimum build against ITK's fixed MeshToPolyData version with CMake flags to enable the remote module?
 - For Python builds, can we build ITKMeshToPolyData against ITK and point ITKBSplineGradient against the correct build tree?

Example 2: ITKUltrasound depends on MeshToPolyData, HigherOrderAccurateGradient, BSplineGradient, SplitComponents, and Strain.
- For cxx: Can we enable all remote modules for ITK to build in the correct order?
- For Python: Can we iteratively build each source in order (ordered list of Git repos, hashes/tags) before building ITKUltrasound?

**Comment by thewtex** [comment]
Another recommended test use / case is ITKTubeTK, which depends on ITKMinimalPathExtraction CC @aylward

**Comment by SimonRit** [comment]
Another one: RTK will depend on ITKCudaCommon (two remote modules) when RTKConsortium/RTK#492 is merged.

**Comment by SimonRit** [comment]
Another one: RTK will depend on ITKCudaCommon (two remote modules) when RTKConsortium/RTK#492 is merged. cc @LucasGandel

**Comment by tbirdso** [comment]
@thewtex @SimonRit Thanks for the feedback. I am guessing that the remote module tags present in ITK (https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/Remote) are not updated quickly enough to be useful here, i.e. it is a requirement that the external module under test can specify a commit hash for each of its ITK module dependencies.

For instance, rather than building ITK with `-DModule_CudaCommon=ON` such that CudaCommon is automatically fetched and built before building RTK, we would rather build ITK -> then fetch CudaCommon at a certain commit tag and build -> then RTK.

Do you agree that it is necessary to allow the user to specify the hash to use for each ITK module dependency?

**Comment by SimonRit** [comment]
If I understand your question correctly, you can specify the module tags manually at configuration with, e.g., `Module_RTK_GIT_TAG`, see [here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKModuleRemote.cmake#L160-L165).

**Comment by dzenanz** [comment]
That is good enough for C++ building and testing. For Python package building it is not so simple.

**Comment by thewtex** [comment]
#tbirdso has implemented this in main, documented in the README.
