### ISSUE TITLE
Create `ITKPythonBuildTestPackageAction` repository

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction#2]
[https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/131](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/131) specifies that ITK remote module CI scripts should be consolidated under composite actions where possible to allow CI across modules to be more easily managed and kept up to date.

Only one composite action may be created per repository. While in theory we could put all cxx and Python CI steps in one `.yml` script with conditionals, it will be easier to manage if cxx and Python steps are kept separate.

One of the two following proposals should be pursued:
1. Create `ITKPythonBuildTestPackageAction` repository with a single `action.yml` to manage build steps for all OS platforms, likely with several conditional steps per OS. Having one repo gives the advantage of consolidating maintenance but the disadvantage of making `action.yml` longer and less readable.
2. Create one repo for each platform (`ITKPythonTestLinuxAction`, `ITKPythonTestWindowsAction`, `ITKPythonTestMacOSAction`) with distinct `action.yml` files. Gives the advantage of distinct actions with minimal conditional logic, disadvantage of greater difficulty of discovery and maintenance.

**Comment by tbirdso** [comment]
@dzenanz @thewtex I'm looking for the go-ahead to create the one or three new InsightSoftwareConsortium repos mentioned inline.

**Comment by dzenanz** [comment]
I have slight preference for option 1.

I think that @jhlegarreta, @hjmjohnson, @blowekamp, and @n-dekker should pitch in, too.

**Comment by N-Dekker** [comment]
Thanks for asking me to have a look. Honestly I'm not a yml or GitHub Actions expert 😃  I'm just wondering, when option 1 is chosen, is it possible/doable to share yml code between the platforms? Personally I find it hard to avoid code duplication in yml files, but that could be my lack of experience!

**Comment by tbirdso** [comment]
Thanks for the feedback all.

> when option 1 is chosen, is it possible/doable to share yml code between the platforms?

@N-Dekker Yes, steps are platform independent by default, we use explicit conditions to run platform-dependent steps. See how we set environment variables in `action.yml`: [https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/blob/main/action.yml#L39](https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/blob/main/action.yml#L39)

Per discussion in https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/131 a reusable workflow in this repo may be able to meet our needs without creating a separate repo for a Python build composite action. Will investigate.

**Comment by tbirdso** [comment]
Following success with our reusable workflow I no longer believe separate repositories are necessary. Closing this issue.
