### ISSUE TITLE
Remove Python 3.7 wheel builds for EOL

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction#60]
Python 3.7 will reach end of life in June 2023. 3.7 builds should be removed from the most recent CI version.

https://devguide.python.org/versions/

Thanks @N-Dekker for bringing this to our attention in https://github.com/InsightSoftwareConsortium/ITKElastix/issues/213#event-9246323199

**Comment by thewtex** [comment]
This will happen in conjunction with ITK-5.4, which will drop 3.7 support in ITK.

**Comment by tbirdso** [comment]
@thewtex What is the estimated release timeframe for ITK 5.4?

**Comment by thewtex** [comment]
@tbirdso June

**Comment by N-Dekker** [comment]
Thanks, I'm looking forward to June  😃 So then, from ITK 5.4.0, just four Python versions need to be supported, right?  Python 3.8, 3.9, 3.10, and 3.11. But then, what if Python 3.12 gets released? (Possibly in October already.) Will we then need to support five Python versions, again?

**Comment by N-Dekker** [comment]
Thanks Tom. Advantages of excluding some of those Python versions while running the CI could be:
- Faster responsiveness of the CI (meaning that a pull request could be merged more quickly)
- Reduced energy consumption (more environment-friendly)

Of course, there is a trade-off. But I wonder if people actually need to have a wheel available as a download, for all supported Python versions, with _each and every_ ITKElastix commit .

**Comment by dzenanz** [comment]
Point of creating the packages in PRs is to make sure it builds - it is one way to test. And different versions have a slightly different set of features, so automated builds can discover that.

I understand the point you make, and do agree that having all the python versions tested is perhaps not necessary. Maybe just the oldest and newest supported version would be enough on PRs?

**Comment by thewtex** [comment]
Python 3.7 support remove it v5.3rc02.
