### ISSUE TITLE
Validate build output fails in my external module

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction#77]
My external module cannot be installed from pypi on my M2 mac, with python 3.10.
I noticed some other external modules can be installed, so I tried to update the hash for the github workflows.
However, I am getting errors in the "Validate build output" step.
https://github.com/dyollb/ITKDissolve/actions/runs/8405014484/job/23017240978

>> InvalidDistribution: Cannot find file (or expand pattern):             
         'dist/itk_*cp38*manylinux_2_28*x86_64.whl'

The failure happens in the linux 3.8 python build. The macos and windows builds succeed.

I did not make any code changes, except for the has in the github workflows. 

Any idea @thewtex?

**Comment by dyollb** [comment]
Ok, so it seems that ITKElastix was probably manually built on arm64 macos. So even if the linux "Validate build output"  error is fixed I still won't have a wheel for my mac m2 from the CI.

**Comment by thewtex** [comment]
@dyollb GitHub Actions recently added support for Apple Silicon ARM GitHub runners. We will look to add support for generating ARM mac wheels for your package in the upcoming release.
